ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
    mongo:
        uri: "mongodb+srv://tcou:tcou@cluster0.rerpv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
        database: "tournament"